#pragma once
#ifndef __GAME_OBJECT_TYPE__
#define __GAME_OBJECT_TYPE__
enum GameObjectType {
	NONE = -1,
	PLAYER,
	EXPLOSION,
	BACKGROUND,
	BULLET,
	ENEMY,
	POWERUP,
	FINISH_LEVEL,
	ENEMY_BULLET,
	LIFE,
	NUM_OF_TYPES,
	BUTTON,
	START_BUTTON,
	INSTRUCTIONS_BUTTON,
	EXIT_BUTTON,
	INSTRUCTIONS_IMAGE
};
#endif /* defined (__GAME_OBJECT_TYPE__) */